name: Packages cleanup
on:
    push:
      branches:
        - main
jobs:
  fetch-packages:
    runs-on: ubuntu-latest

    outputs:
      output: ${{ steps.fetch-packages.outputs.result }}
    steps:        
          - name: Debug
            run: |
              set -x
              result=$(curl -s -H "Authorization: token ${{ secrets.TOKEN }}" \
              "https://api.github.com/orgs/5ire-tech/packages?package_type=container" \
               | jq -r '.[] .name' | tr '\n' ',' | sed 's/,$//' | sed 's/^/[/;s/$/]/') 
               echo "$result<<EOF" >> $GITHUB_OUTPUT
               echo 'EOF' >> $GITHUB_OUTPUT
               echo "::set-output name=result::$result"  # Set the result as an output

  use-matrix:
    needs: fetch-packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ needs.fetch-packages.outputs.result }}
    steps:
      - name: Delete Package
        run: | 
          echo "${{ matrix.package }}"
       







