name: Packages cleanup
on:
    push:
      branches:
        - main
jobs:
  fetch-packages:
    runs-on: ubuntu-latest

    outputs:
      output: ${{steps.step1.outputs.result}}
    steps:        
          - name: Debug
            run: |
              set -x
              result=$(curl -v -s -H "Authorization: token ${{ secrets.TOKEN }}" \
              "https://api.github.com/orgs/hetch-tech/packages?package_type=container" \
              | jq -r '[.[] | select(.name) | .name] | join(", ")')
              echo "$result" >> "$GITHUB_OUTPUT"




