name: Packages cleanup
on:
    push:
      branches:
        - main
jobs:
  fetch-packages:
    runs-on: ubuntu-latest

    outputs:
      result: ${{ steps.step1.outputs.result }}
    steps:        
        - name: Debug
          id: step1
          run: |
            set -x
            result=$(curl -s -H "Authorization: token ${{ secrets.TOKEN }}" \
            https://api.github.com/orgs/5ire-tech/packages?package_type=container\
            | jq -r '.[] .name' | tr '\n' ',' | sed 's/,$//' | sed 's/^/[/;s/$/]/' | tr -d '[]') 
            # # echo "$result<<EOF" >> $GITHUB_OUTPUT
            # echo "$result<<EOF" >> $GITHUB_WORKSPACE/my_result.txt  # Save the result to a file

            # echo 'EOF' >> $GITHUB_WORKSPACE/my_result.txt
            echo "::set-output name=result::$result"  # Set the 'result' output
  use-matrix:
    needs: fetch-packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ["${{ needs.fetch-packages.outputs.result }}"]
    steps:
      - name: packagename
        run : |
           package_names="${{ needs.fetch-packages.outputs.result }}"
           package_array=($package_names)
           matrix_packages=$(echo "${package_array[@]}" | jq -R 'split(",")')
           echo "::set-output name=matrix-packages::${matrix_packages}"
        
      - name: Delete Package
        run : |
            for package in ${{fromJson(steps.create-matrix.outputs.matrix-packages)}}; do
            echo "Deleting package: $package"






