name: Packages cleanup
on:
    push:
      branches:
        - main
jobs:
  fetch-packages:
    runs-on: ubuntu-latest

    outputs:
      result: ${{ steps.step1.outputs.result }}
    steps:        
        - name: Debug
          id: step1
          run: |
            set -x
            result=$(curl -s -H "Authorization: token ${{ secrets.TOKEN }}" \
            https://api.github.com/orgs/5ire-tech/packages?package_type=container\
            | jq -r '.[] .name' | tr '\n' ',' | sed 's/,$//' | sed 's/^/[/;s/$/]/') 
            # echo "$result<<EOF" >> $GITHUB_OUTPUT
            echo "$result<<EOF" >> $GITHUB_WORKSPACE/my_result.txt  # Save the result to a file

            echo 'EOF' >> $GITHUB_WORKSPACE/my_result.txt

        - name: Save to file
          run: |
              echo "$MY_RESULT" >> $GITHUB_WORKSPACE/my_result.txt
        - name: List Workspace Contents
          run: |
                ls -la $GITHUB_WORKSPACE


                             

  use-matrix:
    needs: fetch-packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
          # package: ["${{ needs.fetch-packages.outputs.result }}"]
            package: ["$GITHUB_WORKSPACE/my_result.txt"]
            

         
          
    steps:
    #   steps:
      - name: Wait for File
        run: |
            while [ ! -f $GITHUB_WORKSPACE/my_result.txt ]; do
            sleep 1
            done
      - name: Read and Debug Package Value
        run: |
          result=$(cat $GITHUB_WORKSPACE/my_result.txt)
          echo "Value in matrix.package: $result"







