name: Packages cleanup
on:
    push:
      branches:
        - main
jobs:
  fetch-packages:
    runs-on: ubuntu-latest

    outputs:
      output: ${{steps.step1.outputs.result}}
    steps:        
          - name: install jq
            run: sudo apt-get install jq -y
          - name: Debug
            run: |
              set -x
              result=$(curl -v -s -H "Authorization: token ${{ secrets.TOKEN }}" \
              "https://api.github.com/orgs/5ire-tech/packages?package_type=container"\
              | jq -r'.[].name | join(", ")' > package_names.txt)
              package_names=$(<package_names.txt)
              echo "PACKAGE_NAMES=$package_names" >> $GITHUB_ENV





