name: Packages cleanup
on:
    push:
      branches:
        - main
jobs:
  fetch-packages:
    runs-on: ubuntu-latest

    outputs:
      result: ${{ steps.step1.outputs.result }}
    steps:        
        - name: Debug
          id: step1
          run: |
            set -x
            result=$(curl -s -H "Authorization: token ${{ secrets.TOKEN }}" \
            https://api.github.com/orgs/5ire-tech/packages?package_type=container\
            | jq -r '.[] .name' | tr '\n' ',' | sed 's/,$//' | sed 's/^/[/;s/$/]/') 
            # echo "$result<<EOF" >> $GITHUB_OUTPUT
            echo "$result<<EOF" >> $GITHUB_WORKSPACE/my_result.txt  # Save the result to a file

            echo 'EOF' >> $GITHUB_WORKSPACE/my_result.txt
       
        - name: Upload artifact
          uses: actions/upload-artifact@v2
          with:
           name: my-result-artifact
           path: $GITHUB_WORKSPACE/my_result.txt
  use-matrix:
    needs: fetch-packages
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-result-artifact
          path: $GITHUB_WORKSPACE
            

         
     - name: Read and Debug Package Value
        run: |
          result=$(cat $GITHUB_WORKSPACE/my_result.txt)
          echo "Value in matrix.package: $result"





