name: Packages cleanup
on:
    push:
      branches:
        - main
jobs:
  fetch-packages:
    runs-on: ubuntu-latest

    outputs:
      output: ${{steps.step1.outputs.result}}
    steps:        
          - name: Debug
            run: |
              set -x
              read -s -p "Enter your PAT: MY_PAT"
              result=$(curl -s -H "Authorization: token $MY_PAT" \
              "https://api.github.com/orgs/5ire-tech/packages?package_type=container" \
               | jq -r '.[] .name' | tr '\n' ',' | sed 's/,$//' | sed 's/^/[/;s/$/]/') 
               echo "$result<<EOF" >> $GITHUB_OUTPUT
               echo 'EOF' >> $GITHUB_OUTPUT
  use-matrix:
    needs: fetch-packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{fromJson(needs.fetch-packages.outputs.output)}}
    steps:
      - name: Delete Package
        uses: actions/delete-package-versions@v4
        with: 
          package-name: ${{ matrix.package }}







