name: Packages cleanup
on:
    push:
      branches:
        - main
jobs:
  fetch-packages:
    runs-on: ubuntu-latest
    outputs:
      output: ${{steps.step1.outputs.result}}
    steps:        
        - name: Fetch package
          id: step1
          run: |
            result=$(curl -v -s -H "Authorization: token ${{ secrets.BOT_TOKEN }}" \
            "https://api.github.com/orgs/5ire-tech/packages?package_type=container")
            echo "$result" 
